name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install poetry
      run: pipx install poetry===1.5.1
    - name: Set up python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'poetry'
    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-root
    - name: Run tests
      run: AWS_DEFAULT_REGION=ap-southeast-2 PYTHONPATH=. poetry run pytest tests
