name: Pyright

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  type-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: jakebailey/pyright-action@v2
        with:
          python-version: ${{ matrix.python-version }}
